steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'insa-1-main'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/insa-1:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/insa-1:latest'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'insa-1'
      - '--image'
      - 'gcr.io/$PROJECT_ID/insa-1:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
images:
  - 'gcr.io/$PROJECT_ID/insa-1:latest'
